name: Build and Analyze with SonarQube
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      # Étape 1 : Checkout du code source
      - uses: actions/checkout@v2
 
      # Étape 2 : Lancer SonarQube dans un conteneur Docker
      - name: Start SonarQube
        run: |
          docker run -d --name sonarqube -p 9000:9000 sonarqube:lts
          # Attendre que SonarQube soit prêt
          sleep 30
 
      # Étape 3 : Installer SonarScanner
      - name: Install SonarScanner
        run: |
          curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner-cli.zip
          mv sonar-scanner-4.6.2.2472-linux sonar-scanner
          export PATH="$PATH:$(pwd)/sonar-scanner/bin"
 
      # Étape 4 : Exécuter SonarScanner pour analyser le projet
      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://localhost:9000
        run: |
          sonar-scanner \
            -Dsonar.projectKey=my_project_key \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN
