name: Docker Compose Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 3. Build Docker Compose
      - name: Build Docker Compose
        run: |
          cd $GITHUB_WORKSPACE
          docker-compose up --build -d
