name: Docker Compose Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Clean up existing Docker containers, networks, and volumes
      - name: Clean up Docker containers, networks, and volumes
        run: |
          docker-compose down --volumes --remove-orphans
          docker system prune -f --volumes

      # 3. Build Docker Compose
      - name: Build Docker Compose
        run: |
          cd $GITHUB_WORKSPACE
          docker-compose up --build

      # 4. Run Docker Compose
      - name: Run Docker Compose
        run: |
          cd $GITHUB_WORKSPACE
          docker-compose up -d
