name: Docker Compose Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      # 1. Checkout the repository (to ensure the code is available)
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Build Docker Compose (using cd to ensure you're in the correct directory)
      - name: Build Docker Compose
        run: |
          cd $GITHUB_WORKSPACE
          docker-compose up --build -d
